Repository OntimizeWeb/ontimize-web-ngx-filemanager, pull requests merged in 2023-01, with the labels that each got.

#80 Update release workflows
  .github/workflows/build-ci.yml
  .github/workflows/build-manually.yml
  .github/workflows/build-release.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release-preview.yml
Labels: enhancement

#82 Fixing compatibility with '*ontimize-web-ngx@8.10.0*'
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-filemanager/package.json
  projects/ontimize-web-ngx-filemanager/src/lib/components/filemanager-table/o-filemanager-table.component.html
  projects/ontimize-web-ngx-filemanager/src/lib/components/filemanager-table/o-filemanager-table.component.ts
  projects/ontimize-web-ngx-filemanager/src/lib/components/filemanager-table/table-extended/dialog/changename/change-name-dialog.component.html
  projects/ontimize-web-ngx-filemanager/src/lib/components/filemanager-table/table-extended/dialog/foldername/folder-name-dialog.component.html
  projects/ontimize-web-ngx-filemanager/src/lib/components/filemanager-table/table-extended/o-table-extended.component.html
  projects/ontimize-web-ngx-filemanager/src/lib/components/filemanager-table/table-extended/o-table-extended.component.ts
Labels: bug, dependencies

#79 Release hotfix 8.5.6
  .github/workflows/build-ci.yml
  .github/workflows/build-manually.yml
  .github/workflows/build-release.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release-preview.yml
  CHANGELOG.md
  package-lock.json
  package.json
  projects/ontimize-web-ngx-filemanager/package.json
  projects/ontimize-web-ngx-filemanager/src/lib/components/filemanager-table/o-filemanager-table.component.html
  projects/ontimize-web-ngx-filemanager/src/lib/components/filemanager-table/o-filemanager-table.component.ts
  projects/ontimize-web-ngx-filemanager/src/lib/components/filemanager-table/table-extended/dialog/changename/change-name-dialog.component.html
  projects/ontimize-web-ngx-filemanager/src/lib/components/filemanager-table/table-extended/dialog/foldername/folder-name-dialog.component.html
  projects/ontimize-web-ngx-filemanager/src/lib/components/filemanager-table/table-extended/o-table-extended.component.html
  projects/ontimize-web-ngx-filemanager/src/lib/components/filemanager-table/table-extended/o-table-extended.component.ts
Labels: release
